### ISSUE TITLE
SSA parameters

### ISSUE THREAD

**Issue by KaiserSozo** [dmarienko/chaos#1]
Hi there!
It is a good work on ssa realization here. And I have a few questions about it.
Which version of ssa algorithm has been implemented in your project? What book or work did you follow?

Time serie from 6000 elements with :param dim: embedding dimensions - 720 and :param k: components indexes for reconstruction - 48 and :param e: minimum value to ensure convergence - 50 and forecasting 10 points ahead takes about 25 seconds to predict. So here 2 questions:
1. Can be algorithm optimized somehow using the same environment? (I assume no, because we use scipy.linalg)
2. More valuable. How should I know which values for the parameters are the best? May be some common practice of time serie elements count\elements values dependency or so?

**Comment by dmarienko** [comment]
Hi, thank you for reaching out, actually I used some standard algo description as for basis of this impl (seems I've lost links to docs after moving to new notebook). 

As for forecast method speed - yeah it's really non optimized in sense of speed. Sometimes algo converges very slow. 

As idea to test I could advice you to look at `ssa_predict` method. There I use last know value from original series as some initial estimation of next point. It's not worst approach especially when your series has some autocorrelations.
 
So you could take a look at here:
```
   # here we use previous value as initial estimation
        x = np.append(x, x[-1]) 
        yq = x[-1]
```
and could try to implement more sophisticated methods for obtainig initial estimation. As example you could use averaged values from recent observations or even estimate AR(I)MA model ang use it's prediction as some initial values. 

As for parameters values - what values do you mean  ? If you talk about size of lagging space you might use `ssa_cutoff_order` method. It may give you some initial imaginary about the lagging space dimension.

Hope it helps.
